### ISSUE TITLE
Increase message size

### ISSUE THREAD

**Issue by ABPSoft** [gusavila92/java-android-websocket-client#1]
Hi
How can I increase message size on received data?
thanks

**Comment by gusavila92** [comment]
Hi.
What do you mean by increase message size?

**Comment by ABPSoft** [comment]
When I send message to websocket server, web socket send me a message (reply).

Sometimes that server reply message size is larger than 2 KB, my websocket client not call onMessage event.

**Comment by gusavila92** [comment]
It will probably a bug with that exact message.
Can you send me the messages that you're trying to send and receive? I will debug the library with those messages.

**Comment by ABPSoft** [comment]
Server message just is simple string.
Simple string which its size is 4 KB

**Comment by gusavila92** [comment]
OK. I will try to reproduce your error to see what's going on.

**Comment by gusavila92** [comment]
I finally was able to reproduce the error. It has to do with some particular message sizes and data. Please download the version 1.1.3.
