### ISSUE TITLE
org.json.JSONException: No value for _version

### ISSUE THREAD

**Issue by ibstelix** [gusavila92/java-android-websocket-client#17]
Hello @gusavila92 
thanks for thie great job.
I'm using using an android SDK (for Kuzzle) and your library is embedded in it.
I'm have very frequent disconnexion and i traced back to your library this exception :
org.json.JSONException: No value for _version
in 
But i can't find what is causing this.
Can you help ?

**Comment by ibstelix** [comment]
Sorry the issue is not on java-android-websocket-client side it is related to Kuzzle.
I'm closing it.
BR.

**Comment by gusavila92** [comment]
OK glad to hear that you're using this library!
