### ISSUE TITLE
Use TLSv1.2 in Android 5 and 6

### ISSUE THREAD

**Issue by JorgeDiazP** [gusavila92/java-android-websocket-client#23]
Hi,

I'm using Kuzzle that uses this library as dependency in his Android SDK to create a WebSocket.

I have to do a connection to a server with TLSv1.2. It works except for Android 5 and 6 versions.
I've been trying, after Kuzzle creates a WebSocketClient to set an SSLFactory to force to use TLSv1.2 without success.

Any help would be appreciated.

**Comment by gusavila92** [comment]
I was testing it and I don't see any issue with the library. The TLS handshake is a very complex process and to debug it you can use Wireshark to see in which point the connection is being dropped. Do a deep investigation about the TLS handshake as well as the JSEE reference guide, and try to create you own SSLSocketFactory. For Android I also recommend using ProviderInstaller to install the latest patches and as a last resort enable TLSv1.0 on the server along with the old cipher suites
