### ISSUE TITLE
How to include SSL certificate in this lib!?

### ISSUE THREAD

**Issue by ImanX** [gusavila92/java-android-websocket-client#4]
I'm using your lib for connect to socket protocol, I need include our ssl certificate.
Can I add our certificate to this lib?

**Comment by gusavila92** [comment]
Hi Alireza.

Unfortunately, there is no way to include a SSL certificate now. I'll be
working to fix this as soon as possible.

**Comment by gusavila92** [comment]
Hi. What do you mean by SSL certificate? This certificate is sent by the server, so I'm not sure about your question.
