### ISSUE TITLE
How to respond server ping with a pong ?

### ISSUE THREAD

**Issue by arpanbose** [gusavila92/java-android-websocket-client#5]
Using node.js I'm sending ping to the client 

> ws.ping();

I'm receiving the ping but how to send a pong in response ?

**Comment by gusavila92** [comment]
Unfortunately, there is no way to send a pong frame now. I'll be working to fix this issue.

**Comment by gusavila92** [comment]
You can download the new version 1.2.0. This version contains Ping and Pong frames. Check it out!
